import { Request } from '../types/RequestsList';

export const data: Request[] = [
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
	{
		'id': 1,
		'creation_time': 'creation time',
		'change_time': 'change time',
		'status': 'Filled',
		'side': 'Buy',
		'price': 8.55,
		'amount': 140000,
		'instrument': 'RUB/USD',
	},
];